# spring
spring.application.name=resume
spring.main.banner-mode=OFF
spring.web.error.include-message=always
spring.output.ansi.enabled=ALWAYS

# logger
logging.pattern.console=%clr(%5level){magenta} %clr([${spring.application.name} | %thread]){faint} %clr(%logger){cyan} : %msg%n
