# spring
spring.application.name=resume
spring.main.banner-mode=OFF
spring.web.error.include-message=always
spring.output.ansi.enabled=ALWAYS

# logger
logging.pattern.console=%clr(%5level){magenta} %clr([${spring.application.name} | %thread]){faint} %clr(%logger){cyan} : %msg%n

# i18n
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8

# files
input-folder=input
output-folder=output
